services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: medical_rag_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../Document:/app/Document
      - ../backend:/app/app
      - ./vector_store:/app/vector_store
    networks:
      - medical_network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    container_name: medical_rag_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - medical_network

networks:
  medical_network:
    driver: bridge
